[en]
contentDir = "content/en"
languageName = "English"
languageCode = "en"
weight = 1

[de]
contentDir = "content/de"
languageName = "Deutsch"
languageCode = "de"
weight = 2

[es]
contentDir = "content/es"
languageName = "Deutsch"
languageCode = "es"
weight = 2